### ISSUE TITLE
hierarchical b-spline refinement doesn't work with uniform knotvectors?

### ISSUE THREAD

**Issue by skyforcen73** [gismo/gismo#10]
Hello everybody,

I would like to use the hierarchical b-spline structure of Gismo. But i got the following issue:
I defined a 2D Domain using uniform knotvectors with multiplicity = 1 at the two end knots:

`  real_t a = -0.5;                   // starting knot`
`real_t b = 1.5;                   // ending knot`
   ` unsigned interior = 7;     // number of interior knots`
    `int      degree = 2;`
    `unsigned mult = 1;  // multiplicity at the two end knots`
   ` gsKnotVector<> kv(a,b,interior, mult);`
    `kv.set_degree(degree);`

Then i got the following knotvector:
`[ -0.5 -0.25 0 0.25 0.5 0.75 1 1.25 1.5 ]`

Now i create the hierarchical b-spline structure :
`gsTensorBSplineBasis<2,real_t> tens( kv, kv);`
`gsHBSplineBasis<2,real_t> hb(tens);`

and try to refine the square [0, 0]×[0.5, 0.5]
    `std::vector<unsigned> box;`
    `box.push_back( 1 );`
   ` box.push_back( 0 );`
    `box.push_back( 0 );`
    `box.push_back( 4 );`
    `box.push_back( 4 );`
   `hb.refineElements(box);`

After exporting to a paraview file. 
`gsWriteParaview(hb, "test_hb_refined" );`

The region which was refined ist [0, 0] x [0.25, 0.25] and not [0, 0]×[0.5, 0.5]. Did i use the wrong indices for the box of refined region or the "refineElements" function only works with knotvectors with multiplicity = degree + 1 at the endknots?

Many thanks in advance!
skyforcen73

**Comment by filiatra** [comment]
Hi skyforcen73,

I guess the issue here is that
refineElements( std::vector<unsigned> )
uses the knot indices of the level that you want the box to be at (not of the "original" level).

In your example, the knot vectors
[-0.5 -0.25 0 ... 1.25 1.5 ]
in each direction have a total of 9 entries each, which have indices 0 to 8 and define level 0.

On level 1, the know vectors will be 
[-0.5 -0.375 -0.25 -0.125 0 ... 1.25 1.375 1.5]
with a total 17 entries, which have indices 0 to 16.

If you want to refine the lower left quarter of the domain, it is defined by the lower corner [0,0] and the upper coner [4,4] on level 0(!), but by the lower corner [0,0] and the upper corner [8,8] on level 1. Hence, if you want to refine the lower left quarter to level 1, "box" should be [1 0 0 8 8].

If you actually want to refine the area with lower corner at COORDINATES [0,0] and upper corner at [0.5, 0.5], it would be defined by the knots with indices [2,2] for the lower corner, and [4,4] for the upper corner on level 0, i.e., to refine to level 1, "box" should be [1 4 4 8 8].

**Comment by skyforcen73** [comment]
hi filiatra,

thank you for your answer!

I have already tried your suggestion for this problem. 

After refining the box [1 4 4 8 8] and exporting to paraview. The region which was refined is [0.25, 0.75] x [0.25, 0.75]. And the box [1 0 0 8 8] just refined the region [0, 0.75] x [0, 0.75].

Maybe the function gsWriteParaview does not work with single end-knots?

**Comment by filiatra** [comment]
It seems that this is a bug, can be related to the single-ended knots. I will try to fix it and come back to you, as well as with info to export the char. matrices,

**Comment by skyforcen73** [comment]
many thanks for your help!

**Comment by dominik-mokris-mtu** [comment]
If I'm correct, the solution I proposed to issue #350 should solve this one as well.
