### ISSUE TITLE
Need some help about a proof.

### ISSUE THREAD

**Issue by arungoooo112** [gismo/gismo#479]
Hi, everyone:

Here is a Proof:
Proof: For the (hb/thb) spline basis function (B1, B2, ... , Bn), there is a set concluding different parameter points (a1, a2, ...,an) satified Bi(ai) is not equal to 0, making (n x n) square matrix C reversible, where Cij = Bj(ai).

I have demonstrated that matrix C, constructed by the nurbs basis function, is reversible through Schoenberg-Whitney Conditions. My job is to extend this nature to the (hb/thb) spline basis function. But it's too hard for me.I know C can be directly calculated by using the gismo funtion collectionMatrix. A large number of tests show that matrix C is reversible.

Until now this proof still bothers me, hoping to get your help.

Frank. 
: )

**Comment by filiatra** [comment]
It is an interesting question.. Note that the question is basis-dependent.
Already I guess we may limit ourselves to p=2 for now. For the HB this seems true, since the Greville points are associated directly to the basis function. But for THB this is more tricky, since the support reduction might give some extra zeros and destroy the matrix..

**Comment by filiatra** [comment]
Hi again, we could discuss this more - you can send me a private message if you wish. My address is just filiatra and it is a gmail account.

**Comment by arungoooo112** [comment]
Hi,

**Comment by arungoooo112** [comment]
Hi, I sent you a email about this issue a few days ago, please check it.

**Comment by arungoooo112** [comment]
@filiatra Hi, I sent you a email about this issue a few days ago, please check it.
